CC	= gcc
CFLAGS	= -g -Wall
PROGS	= sortViaMerge sortViaSelection

all:	$(PROGS)

clean:;	$(RM) $(PROGS) *.o core

sortViaSelection:	sortViaSelection.c
	$(CC) -o sortViaSelection sortViaSelection.c

sortViaMerge:	sortViaMerge.c
	$(CC) -o sortViaMerge sortViaMerge.c
